# conda environment description for Python packages and environments
# session
#
# Create a conda environment in which the notebooks in this repo can be run
# with
#
#   conda env create -f environment.yaml

name: moad-pkgs-envs

channels:
  - conda-forge

dependencies:
  - notebook
  - python=3
  - rise
  # A packaging issue on 23-May-2023 made it necessary to list the following dependencies
  # explicitly. It is to be hoped that this situation is temporary.
  - webcolors
  - uri-template
  - jsonpointer
  - isoduration
  - fqdn

